"""Figure export.

Vector PDF first (that is what a camera-ready IEEE submission wants), plus a
high-resolution PNG for quick inspection.  Every figure is saved from a saved
*result file*, never from numbers held only in memory, so any figure can be
regenerated by ``scripts/generate_all_figures.py`` without re-running an
experiment.
"""

from __future__ import annotations

from collections.abc import Sequence
from pathlib import Path
from typing import Any

import matplotlib.pyplot as plt

DEFAULT_FORMATS = ("pdf", "png")


def save_figure(
    fig,
    path_stem: Path | str,
    *,
    formats: Sequence[str] = DEFAULT_FORMATS,
    dpi: int = 400,
    close: bool = True,
) -> list[str]:
    """Save ``fig`` as ``<path_stem>.<fmt>`` for each requested format."""
    stem = Path(path_stem)
    stem.parent.mkdir(parents=True, exist_ok=True)
    written: list[str] = []
    for fmt in formats:
        out = stem.with_suffix(f".{fmt}")
        fig.savefig(out, format=fmt, dpi=dpi, bbox_inches="tight", pad_inches=0.02)
        written.append(str(out))
    if close:
        plt.close(fig)
    return written


def figure_index(paths: Sequence[str]) -> list[dict[str, Any]]:
    """A JSON-serialisable index of produced figures, for the run manifest."""
    out = []
    for p in paths:
        path = Path(p)
        out.append(
            {
                "path": str(path),
                "name": path.stem,
                "format": path.suffix.lstrip("."),
                "bytes": path.stat().st_size if path.exists() else None,
            }
        )
    return out
